[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
preDeployCommand = ["npx prisma migrate deploy"]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 60
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
